### ISSUE TITLE
set_connection is public static function outside of the constructor

### ISSUE THREAD

**Issue by Mohammed-Elmasry** [SalmaMeniawy/E-mall#1]
the set_connection() function is a wrapper function designed to give an interface for the class' user to be able to invoke the constructor __construct() indirectly, placing it within the constructor makes no sense as it will not be accessible. It should instead be a public static function that returns the connection object created from the private call to the constructor if exists and creates it by calling the constructor in case the DB connection object equals NULL.

**Comment by SalmaMeniawy** [comment]
the issue fixed .. now the method create connection call the constructor and give parameters to him because it is private constructor ..
